apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    app: kube2iam
spec:
  selector:
    matchLabels:
      name: kube2iam
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: kube2iam
      tolerations:
      - operator: Exists
      hostNetwork: true
      containers:
        - image: {{ .Values.kube2iam.image }}:{{ .Values.kube2iam.tag }}
          imagePullPolicy: IfNotPresent
          name: kube2iam
          args:
            - "--auto-discover-base-arn"
            - "--auto-discover-default-role=true"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--host-interface=eni+"
            - "--namespace-restrictions"
            - "--node=$(NODE_NAME)"
            - "--use-regional-sts-endpoint"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true
            procMount: Default
