---
- name: apply all cluster-level settings and applications
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
  - name: include all vault encrypted variables
    include_vars:
      dir: vault_vars
    tags: always
    when: use_vault | default(false)

  - name: Print some debug information
    vars:
      msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}

    debug:
      msg: "{{ msg.split('\n') }}"
    tags: debug_info

  tasks:
  - import_tasks: aws-auth.yml
    tags: auth
  - import_tasks: kube2iam.yml
    tags: kube2iam
  - import_tasks: cluster-autoscaler.yml
    tags: cluster-autoscaler
  - import_tasks: php.yml
    tags: php